CREATE TABLE A (
  A_EDGE    INT PRIMARY KEY,
  A_CRD0    INT,
  A_CRD1    INT,
  A_VAL     FLOAT
);

CREATE TABLE B1 (
  B1_CRD0    INT,
  B1_CRD1    INT,
  B1_VAL     FLOAT,
  PRIMARY KEY (B1_CRD0, B1_CRD1)
);

CREATE TABLE B2 (
  B2_CRD0    INT,
  B2_CRD1    INT,
  B2_VAL     FLOAT,
  PRIMARY KEY (B2_CRD0, B2_CRD1)
);